CREATE DATABASE NAVESESPACIALES;
USE NAVESESPACIALES;

CREATE TABLE TIPOS_TRIPULACION(
	TRIPU_ID VARCHAR(9) PRIMARY KEY,
	NOMBRE VARCHAR(20)
)

INSERT INTO TIPOS_TRIPULACION VALUES 
('TRIPU_ID1', 'TRIPULADAS'),
('TRIPU_ID2', 'NO TRIPULADAS');


CREATE TABLE PAISES(
PAIS_ID VARCHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(20)
)

INSERT INTO PAISES VALUES
('PAIS_ID1','RUSIA'),
('PAIS_ID2','USA'),
('PAIS_ID3','ALEMANIA'),
('PAIS_ID4','JAPON'),
('PAIS_ID5','CHINA');


CREATE TABLE TIPOS_NAVES (
TN_ID VARCHAR(8) PRIMARY KEY,
NOMBRE VARCHAR(60),
DESCRIPCION VARCHAR(160),
ID_T_TRIPULACION VARCHAR(9),

FOREIGN KEY(ID_T_TRIPULACION) REFERENCES TIPOS_TRIPULACION(TRIPU_ID)
);


INSERT INTO TIPOS_NAVES VALUES 
('TIPO_ID1','VEHICULOS LANZADERA','SIRVE PARA LANZAR CARGA UTIL AL ESPACIO','TRIPU_ID1'),
('TIPO_ID2','NAVES NO TRIPULADAS','ESTAN HECHOS PARA PODER ESTUDIAR CUERPOS CELESTES','TRIPU_ID2'),
('TIPO_ID3','NAVES ESPACIALES TRIPULADAS','SU PROPOSITO ES ENVIAR HUMANOS AL ESPACIO PARA QUE PUEDAN CUMPLIR CON DETERMINADAS TAREAS','TRIPU_ID1');


CREATE TABLE FUENTES_ENERGIA(
ID VARCHAR(7) PRIMARY KEY,
NOMBRE VARCHAR(40)
);

INSERT INTO FUENTES_ENERGIA VALUES
('FE_ID1','QUIMICO SOLIDO'),
('FE_ID2','PROPELENTE LIQUIDO'),
('FE_ID3','CELDAS FOTOVOLTAICAS'),
('FE_ID4','PETROLEO REFINADO'),
('FE_ID5','OXIGENO LIQUIDO'),
('FE_ID6','OXIDO DE NITROGENO'),
('FE_ID7','DIMETILHIDRACINA'),
('FE_ID8','LIQUIDO DE HIDROGENO'),
('FE_ID9','LIQUIDO DE OXIGENO'),
('FE_ID10','OXIDO NITRICO'),
('FE_ID11','TETROXIDO DE NITROGENO'),
('FE_ID12','HIDRACINA');


CREATE TABLE NAVES(
ID_NAVE VARCHAR(7) PRIMARY KEY,
TIPO_NAVE_ID VARCHAR(8),
DESCRIPCION VARCHAR(120),
VELOCIDAD INT,
FUENTE_ENERGIA_ID VARCHAR(7),
TRIPULANTES INT,
PAIS_ID VARCHAR(9),

FOREIGN KEY(TIPO_NAVE_ID) REFERENCES TIPOS_NAVES(TN_ID),
FOREIGN KEY(FUENTE_ENERGIA_ID) REFERENCES FUENTES_ENERGIA(ID),
FOREIGN KEY(PAIS_ID) REFERENCES PAISES(PAIS_ID)
);




